name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configure AWS Credentials
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 615299765743.dkr.ecr.ap-south-1.amazonaws.com

    # Build Docker Image and Push
    - name: Build and Push Docker Image
      run: |
        IMAGE_TAG=615299765743.dkr.ecr.ap-south-1.amazonaws.com/killiansclub-server:${{ github.sha }}
        docker build -t $IMAGE_TAG . 
        docker push $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # Update EKS Deployment
    - name: Update EKS Deployment
      run: |
        aws eks update-kubeconfig --region ap-south-1 --name killians-club
        kubectl set image deployment/deployment hello-world=615299765743.dkr.ecr.ap-south-1.amazonaws.com/killiansclub-server:$IMAGE_TAG --record
        kubectl rollout status deployment/deployment
